"""added many to many field for likes

Revision ID: 0e84265d5d11
Revises: 59064e645bc9
Create Date: 2022-02-14 17:11:38.350318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e84265d5d11'
down_revision = '59064e645bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_like',
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('like_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['like_id'], ['like.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_like')
    # ### end Alembic commands ###
