"""add namespace and color field to Tag

Revision ID: fd974b377a44
Revises: 8fccc4de1ee0
Create Date: 2022-01-29 15:57:28.738634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd974b377a44'
down_revision = '8fccc4de1ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('namespace', sa.Text(), nullable=True))
    op.add_column('tag', sa.Column('color', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'color')
    op.drop_column('tag', 'namespace')
    # ### end Alembic commands ###
