# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Flask-Migrate Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Setup
      run: |
        python -m venv env
        source env/bin/activate
        echo "VIRTUAL ENV:" $VIRTUAL_ENV
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        ls env/lib/python3.10/site-packages
        cp template.env .env
    - name: Flask-Migrate
      run: |
        source env/bin/activate
        echo "VIRTUAL ENV:" $VIRTUAL_ENV
        flask db migrate
        flask db upgrade
